### ISSUE TITLE
Undefined 

### ISSUE THREAD

**Issue by h4818** [tsega/meteor-bootstrap3-datetimepicker#23]
I'm using autoform and datetimepicker and with the following code: 

``` html
{{> quickForm collection="xxx" id="insertxxxForm" type="insert" omitFields="time_listed, owner, participants"}}
```

``` javascript
time_start: {
        type: Date,
        label: "Start Time",
        autoform: {
            type: "bootstrap-datetimepicker"
        }
    },
    time_end: {
        type: Date,
        label: "End Time",
        autoform: {
            type: "bootstrap-datetimepicker"
        }
    },
```

I seem to get the following error:

```
Exception from Tracker afterFlush function: Cannot read property 'getDate' of undefined
TypeError: Cannot read property 'getDate' of undefined
    at AutoForm.addInputType.valueOut (http://localhost:3000/packages/francocatena_autoform-bs-datetimepicker.js?26b0f499c5aa0c176cd5bd238329a84be6bc1095:73:42)
    at Object.autoFormGetInputValue [as getInputValue] (http://localhost:3000/packages/aldeed_autoform.js?14f33a142f5bfdfae4b68bc342a10f1c64fa682d:2305:28)
```

When it does go through, autoform validation fails because time_start is required

**Comment by ddela-cr** [comment]
@tsega I'm having the same issue, i did that afFieldInput part.

`    arrival: {
    		type: Flight_Info,
	  	optional: true,
		label: 'Arrival',
		autoform:{
			group: '3 Informations supplementaires',
			afFieldInput: {
		        type: "bootstrap-datetimepicker",
		        timezoneId: "Europe/Paris"
	    	}
		}
	},
	departure: {
		type: Flight_Info,
		optional: true,
		label: 'Departure',
		autoform:{
			group: '3 Informations supplementaires',
			afFieldInput: {
		        type: "bootstrap-datetimepicker",
		        timezoneId: "Europe/Paris"
	    	}
		}
	},`

here is my Flight_Info schema

`Flight_Info = new SimpleSchema({
	date: {
		type: Date,
		optional: true,
		autoform: {
			group: '3 Informations supplementaires',
		    afFieldInput: {
		        type: "bootstrap-datetimepicker",
		        timezoneId: "Europe/Paris"
	    	}
	    }
	},
	place: {
		type: String,
		optional: true,
		autoform:{
			group: '3 Informations supplementaires'
		}
	}
});`


`TypeError: Cannot read property 'getDate' of undefined
    at AutoForm.addInputType.valueOut (aldeed_autoform-bs-datetimepicker.js:56)`

**Comment by tsega** [comment]
Do you have [mrt:moment-timezone](https://atmospherejs.com/mrt/moment-timezone) package installed? According to [the aldeed:autoform-bs-datetimepicker docs](https://github.com/aldeed/meteor-autoform-bs-datetimepicker), you need it.

**Comment by ddela-cr** [comment]
I do. It works well on the insert form. It only does this on the update form

**Comment by tsega** [comment]
Can you create a sample app on github that I can help you with, MeteorPad.com could have been a great help right about now 😞

**Comment by ddela-cr** [comment]
shared the repo with you

**Comment by ddela-cr** [comment]
shared the repo with you, please feel free to contant me at daviddlcz25@gmail.com if you cant figure out navigation on the app, thanks
