### ISSUE TITLE
option language: "ru" does not work

### ISSUE THREAD

**Issue by comerc** [tsega/meteor-bootstrap3-datetimepicker#24]
Uncaught TypeError: Cannot read property 'postformat' of null

``` coffee
        dateTimePickerOptions:
          language: "ru"
```

**Comment by lugaru90** [comment]
I'm trying to change the language with: data-date-language='de' but its not working. No error, just still in english. I've added rzymek:moment-locale-de and using autoform. Any Ideas? 
PS:data-date-format= is working!
```{> afQuickField name='date' type="bootstrap-datepicker" data-date-format='dd.mm.yyyy' data-date-language="de-DE"}}```

**Comment by tsega** [comment]
@lugaru90 from the snippet above, I see you're using the [Date Picker](https://atmospherejs.com/rajit/bootstrap3-datepicker) package as opposed to this package, i.e. the **Date _Time_ Picker** package. 

Next, going to the [documentation page](http://bootstrap-datepicker.readthedocs.org/en/release/i18n.html) of the JavaScript library of @rajit 's Meteor package, you will see that you need to add the exact language script file of the library for the localization to work.

One other thing I couldn't find is how the [autoform](https://github.com/aldeed/meteor-autoform) package in general, and the [AutoForm Bootstrap Date Picker](https://github.com/aldeed/meteor-autoform-bs-datepicker) package in particular, handle language options. This we need to ask in the appropriate repositories.

**Comment by comerc** [comment]
@tsega, try [v4beta](https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/7)
