### ISSUE TITLE
showClear option doesn't seem to work

### ISSUE THREAD

**Issue by hujhax** [tsega/meteor-bootstrap3-datetimepicker#27]
The documentation for the bootstrap 3 datetimepicker lists the following:

    showClear
    Default: false
    Show the "Clear" button in the icon toolbar.

    Clicking the "Clear" button will set the calendar to null.
    
I've tried creating a datetimepicker in my meteor project:

    var initDateTimePicker = function(selection) {
        return selection.datetimepicker({format: formatString, sideBySide: true, showClear: true});
    };
    
... while sideBySide works fine, showClear has no effect.

**Comment by hujhax** [comment]
Here's a jsfiddle that shows the correct behavior:
http://jsfiddle.net/x56yo0yy/

Maybe we just need the latest version of the Eonasdan plugin?

**Comment by hujhax** [comment]
I think I have a fix [here](https://github.com/hujhax/meteor-bootstrap3-datetimepicker/tree/b7ba6f6bcae8668c6ccbd1e79a9b41ec857de39d).

**Comment by tsega** [comment]
@hujhax thanks for identifying the issue, I just updated the package to use the latest version of the library and now it works as expected. Checkout my [sample meteor pad](http://meteorpad.com/pad/kfrjjWchgmKYw7kZH/AutoForm%20and%20BDTP%20Sample), BTW MeteorPad.com is JS Fiddle for Meteor.

**Comment by hujhax** [comment]
Perfect!  Thanks.
