### ISSUE TITLE
Picker shows calendar for time-only entry

### ISSUE THREAD

**Issue by hujhax** [tsega/meteor-bootstrap3-datetimepicker#28]
When the format is time-only, the picker is supposed to suppress the calendar interface.  Here is a jsfiddle showing the proper behavior:
http://jsfiddle.net/x56yo0yy/

In the plugin, when we use a time-only format, it shows the calendar and the calendar button.

**Comment by hujhax** [comment]
I think I have a fix at https://github.com/hujhax/meteor-bootstrap3-datetimepicker/.

**Comment by tsega** [comment]
Thanks again, this too is fixed after the update. Please check [here](http://meteorpad.com/pad/kfrjjWchgmKYw7kZH/AutoForm%20and%20BDTP%20Sample).
