### ISSUE TITLE
Datetimpicker don't bind to ng-model properly

### ISSUE THREAD

**Issue by philonaut** [tsega/meteor-bootstrap3-datetimepicker#30]
had some trouble with the datetimepicker in combination with the urigo:angular package. When I pick a date the model won't get updated example on:
https://github.com/philonaut/meteor-angular-bootstrap

Probably it is my fault, im new to this technology

**Comment by tsega** [comment]
@philonaut it would be good if you could have a running example, [MeteorPad](http://meteorpad.com/) is a good tool to use for such purposes. Personally I have not used Angular or urigo:angular with Meteor, but have you tried [urigo:angular-ui-bootstrap-calendar](https://atmospherejs.com/urigo/angular-ui-bootstrap-calendar)?

**Comment by opbt-hog** [comment]
When used with the containing div positioned relative the widget appears as the last element in my form. Otherwise appears normally but pushes all elements after it to be below it.

**Comment by tsega** [comment]
@opbt-hog could you try the updated one (v 4.7.14_2), it has some CSS updates and that might do the trick. Please get back to me if the problem persists.

**Comment by opbt-hog** [comment]
I tried update via meteor update and it won't get the new version. I tried
to replace just the CSS file and Meteor just complained about a missing {
near line 319 in that file which I can't see. Is there another way to
update to this version?

On Tue, Mar 17, 2015 at 1:56 PM, Tsegaselassie Tadesse <
notifications@github.com> wrote:

> @opbt-hog <https://github.com/opbt-hog> could you try the updated one (v
> 4.7.14_2), it has some CSS updates and that might do the trick. Please get
> back to me if the problem persists.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsega/meteor-bootstrap3-datetimepicker/issues/30#issuecomment-82527672>
> .
>



-- 
Harley Harrington
4227 S 13th St
Sheboygan, WI 53081

Google Voice:262-528-2147
Email: harley@harleyhar.com

**Comment by tsega** [comment]
@opbt-hog yeah sometimes the `meteor update` doesn't update your packages, you might want to remove the package first and then add it again. Hit me up how that goes.

**Comment by opbt-hog** [comment]
tsega:bootstrap3-datetimepicker  added, version 4.0.0_4

On Tue, Mar 17, 2015 at 3:34 PM, Tsegaselassie Tadesse <
notifications@github.com> wrote:

> @opbt-hog <https://github.com/opbt-hog> yeah sometimes the meteor update
> doesn't update your packages, you might want to remove the package first
> and then add it again. Hit me up how that goes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsega/meteor-bootstrap3-datetimepicker/issues/30#issuecomment-82585725>
> .
>



-- 
Harley Harrington
4227 S 13th St
Sheboygan, WI 53081

Google Voice:262-528-2147
Email: harley@harleyhar.com

**Comment by tsega** [comment]
@opbt-hog I totally forgot to do `meteor publish` please try updating now, it should work!

**Comment by opbt-hog** [comment]
That did install the correct version. Meteor updated a whole bunch of other
packages as well and now my app crashes. Once I get that figured out I will
let you know if this fixed the issue.

Thanks!

On Tue, Mar 17, 2015 at 4:10 PM, Tsegaselassie Tadesse <
notifications@github.com> wrote:

> @opbt-hog <https://github.com/opbt-hog> I totally forgot to do meteor
> publish please try updating now, it should work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsega/meteor-bootstrap3-datetimepicker/issues/30#issuecomment-82602294>
> .
>



-- 
Harley Harrington
4227 S 13th St
Sheboygan, WI 53081

Google Voice:262-528-2147
Email: harley@harleyhar.com

**Comment by opbt-hog** [comment]
unfortunately I think it may be the date picker that is causing the app to
crash. I really can't make sense of all the error stuff here-

=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
^C
harleyhar@ip-104-238-125-205 [~/onepage]# meteor add
tsega:bootstrap3-datetimepicker

Changes to your project's package version selections:

tsega:bootstrap3-datetimepicker  added, version 4.7.14_3


tsega:bootstrap3-datetimepicker: Bootstrap 3 DateTime picker from @Eonasdan,
packaged for Meteor.js
harleyhar@ip-104-238-125-205 [~/onepage]# meteor
[[[[[ ~/onepage ]]]]]

=> Started proxy.
=> Started MongoDB.

/home/harleyhar/.meteor/packages/meteor-tool/.1.0.43.pv9wg1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at Object.exports.spawn (child_process.js:746:9)
    at [object Object]._.extend._spawn
(/home/harleyhar/.meteor/packages/meteor-tool/.1.0.43.pv9wg1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:254:31)
    at [object Object]._.extend.start
(/home/harleyhar/.meteor/packages/meteor-tool/.1.0.43.pv9wg1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:84:22)
    at [object Object]._.extend._runOnce
(/home/harleyhar/.meteor/packages/meteor-tool/.1.0.43.pv9wg1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:701:16)
    at [object Object]._.extend._fiber
(/home/harleyhar/.meteor/packages/meteor-tool/.1.0.43.pv9wg1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:821:28)
    at
/home/harleyhar/.meteor/packages/meteor-tool/.1.0.43.pv9wg1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:402:12


On Tue, Mar 17, 2015 at 4:10 PM, Tsegaselassie Tadesse <
notifications@github.com> wrote:

> @opbt-hog <https://github.com/opbt-hog> I totally forgot to do meteor
> publish please try updating now, it should work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsega/meteor-bootstrap3-datetimepicker/issues/30#issuecomment-82602294>
> .
>



-- 
Harley Harrington
4227 S 13th St
Sheboygan, WI 53081

Google Voice:262-528-2147
Email: harley@harleyhar.com

**Comment by tsega** [comment]
According to this [stackoverflow question](http://stackoverflow.com/questions/20857283/meteor-cant-run-server) that error happens when Meteor runs out of memory. As suggested by the answer, please try to increase the memory available for Meteor. 

I would also recommend shutting down your machine and restarting, just in case.

**Comment by opbt-hog** [comment]
I have 600 MB available. That should be enough?

On Thu, Mar 19, 2015 at 3:27 AM, Tsegaselassie Tadesse <
notifications@github.com> wrote:

> According to this stackoverflow question
> <http://stackoverflow.com/questions/20857283/meteor-cant-run-server> that
> error happens when Meteor runs out of memory. As suggested by the answer,
> please try to increase the memory available for Meteor.
>
> I would also recommend shutting down your machine and restarting, just in
> case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsega/meteor-bootstrap3-datetimepicker/issues/30#issuecomment-83413996>
> .
>



-- 
Harley Harrington
4227 S 13th St
Sheboygan, WI 53081

Google Voice:262-528-2147
Email: harley@harleyhar.com

**Comment by tsega** [comment]
Are you on a VPS or something like that? If so it might be a good idea to increase the available RAM and see if it fixes the problem. I'm not exactly sure of how much is needed though. Maybe try with something like 1GB or 2GB but be sure to ask in the [Meteor forums](https://forums.meteor.com) if the problem persists.

**Comment by opbt-hog** [comment]
OK, thanks.

On Thu, Mar 19, 2015 at 9:49 AM, Tsegaselassie Tadesse <
notifications@github.com> wrote:

> Are you on a VPS or something like that? If so it might be a good idea to
> increase the available RAM and see if it fixes the problem. I'm not exactly
> sure of how much is needed though. Maybe try with something like 1GB or 2GB
> but be sure to ask in the Meteor forums <https://forums.meteor.com> if
> the problem persists.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsega/meteor-bootstrap3-datetimepicker/issues/30#issuecomment-83614007>
> .
>



-- 
Harley Harrington
4227 S 13th St
Sheboygan, WI 53081

Google Voice:262-528-2147
Email: harley@harleyhar.com

**Comment by opbt-hog** [comment]
Upgraded our VPS to 2GB and now your date time picker is back to normal.

What do you do in your spare time? We are looking for someone who would be
interested in helping us finish our app. This has been a learning process
for me - http://onepageaccounting.com/

On Thu, Mar 19, 2015 at 9:59 AM, Harley Harrington <harleyhar.com@gmail.com>
wrote:

> OK, thanks.
>
> On Thu, Mar 19, 2015 at 9:49 AM, Tsegaselassie Tadesse <
> notifications@github.com> wrote:
>
>> Are you on a VPS or something like that? If so it might be a good idea to
>> increase the available RAM and see if it fixes the problem. I'm not exactly
>> sure of how much is needed though. Maybe try with something like 1GB or 2GB
>> but be sure to ask in the Meteor forums <https://forums.meteor.com> if
>> the problem persists.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tsega/meteor-bootstrap3-datetimepicker/issues/30#issuecomment-83614007>
>> .
>>
>
>
>
> --
> Harley Harrington
> 4227 S 13th St
> Sheboygan, WI 53081
>
> Google Voice:262-528-2147
> Email: harley@harleyhar.com
>



-- 
Harley Harrington
4227 S 13th St
Sheboygan, WI 53081

Google Voice:262-528-2147
Email: harley@harleyhar.com
