### ISSUE TITLE
Missing font dependencies? Picker glyphs not showing correctly.

### ISSUE THREAD

**Issue by gb96** [tsega/meteor-bootstrap3-datetimepicker#33]
Please see attached screenshots.  Should the meteor package include dependencies on bootstrap3, font awesome and/or glyphicons-halflings or something.

Picker is working fine except none of the glyphs show...

Have tried adding font-packages (e.g. chriswessels:glyphicons-halflings 2.0.0, natestrauser:font-awesome 4.3.0) but not sure what's required so hoping you could help?

There are a few different meteor bootstrap packages around (https://atmospherejs.com/tsega/bootstrap3-datetimepicker?q=bootstrap) not sure if I need to install one of these or not. New to bootstrap so not sure what to do to fix the glyphs.
![missing-fonts-1](https://cloud.githubusercontent.com/assets/526473/6775235/e65a2b54-d17d-11e4-83f2-a27a2d0eb108.png)
![missing-fonts-2](https://cloud.githubusercontent.com/assets/526473/6775234/e65a0fe8-d17d-11e4-8167-1a5136498705.png)

**Comment by tsega** [comment]
@gb96 you're correct in saying that you need to install a bootstrap plugin, that is a required dependency. You can try out any of them. An important thing to note in choosing any package in meteor is to see the popularity of that package using the mini graph. 

If you are new to bootstrap, you can try out simpler packages like, [mrt:bootstrap-3](https://atmospherejs.com/mrt/bootstrap-3) it looks quite propular and I believe it's maintained by a regular contributor, @mizzao. As you get comfortable with bootstrap, however, I would recommend you give [nemo64:bootstrap](https://atmospherejs.com/nemo64/bootstrap) a try.

**Comment by mizzao** [comment]
No, don't use `mrt:bootstrap-3`; use `twbs:bootstrap`.

**Comment by tsega** [comment]
Thanks for pointing that out @mizzao

**Comment by gb96** [comment]
Thanks for the suggestions @mizzao and @tsega however using any of the bootstrap-3 packages you recommend causes the datetimepicker modal window to not display at all.  All that happens is the web page goes dark (like there is a drop-shadow over all of it) but no modal picker component visible.

I have tried the following bootstrap-3 meteor packages, but none of them work for me:
1. twbs:bootstrap (3.3.4)
2. mrt:bootstrap-3 (0.3.8)
3. foldor:bootstrap-3 (3.2.0)
4. pahans:bootstrap-3 (3.2.0)
5. yogiben:bootstrap (0.3.9)
6. twbs:bootstrap-noglyph (3.3.2)
7. simison:bootstrap3-less (0.3.0)

Have ended up going back to using package bootstrap (1.0.1) because at least the datetimepicker is usable (even without glyphs)

**Comment by gb96** [comment]
Saw this in the Chrome JavaScript console, perhaps this is my original problem:

```javascript
Resource interpreted as Font but transferred with MIME type text/html: "http://localhost:3000/packages/glyphicons-halflings/lib/glyphicons-halflings/fonts/glyphicons-halflings-regular.woff".jquery.js:6159 curCSSjquery.js:6751 jQuery.extend.cssjquery.js:6774 jQuery.each.jQuery.cssHooks.(anonymous function).getjquery.js:6746 jQuery.extend.cssjquery.js:10273 (anonymous function)jquery.js:4177 jQuery.accessjquery.js:10248 jQuery.each.jQuery.each.jQuery.fn.(anonymous function)bootstrap3-datetimepicker.js:380 placebootstrap3-datetimepicker.js:1021 showjquery.js:4665 jQuery.event.dispatchjquery.js:4333 jQuery.event.add.elemData.handle
```

**Comment by gb96** [comment]
Okay, the message 'Resource interpreted as Font but transferred with MIME type text/html: "http://localhost:3000/packages/glyphicons-halflings/lib/glyphicons-halflings/fonts/glyphicons-halflings-regular.woff"' means that Meteor served up a 404 page (MIME type text/html) instead of the actual font  (application/font-woff)

**Comment by mizzao** [comment]
You need a bootstrap package that serves up the right font paths. This used to require a workaround (https://github.com/mizzao/meteor-bootstrap-3/blob/master/package.js) but that went away in later versions of Meteor; maybe it is a regression.

**Comment by gb96** [comment]
I have got the datetimepicker glyphs to work now.  Steps I took to fix (not necessarily the best solution):
1. meteor add chriswessels:glyphicons-halflings  # version 2.0.0  This simple smart package adds the Glyphicon Halflings font-face to Meteor.
2. Copy the 4 font files found under `.meteor/local/build/programs/web.browser/packages/chriswessels_glyphicons-halflings/lib/glyphicons-halflings/fonts/` to `public/packages/glyphicons-halflings/lib/glyphicons-halflings/fonts/`

**Comment by mizzao** [comment]
**EDIT**: Yeah, they definitely broke it. The paths with the `dist/` don't represent files that can be directly sent to the client. Instead they must be added as assets with paths that correspond in the CSS, hence I'd be very surprised if those fonts were found.

@dandv: how did the bootstrap files end up with `api.addFiles('dist/fonts/glyphicons-halflings-regular.woff')`, etc?

@gb96 your workaround might work now but it is brittle and will probably break later.

**Comment by tsega** [comment]
I have used [pfafman:bootstrap-3](https://github.com/pfafman/meteor-bootstrap-3) with no issues, I can't find it on atmosphere though, that's kind weird!
