### ISSUE TITLE
Locale not working.

### ISSUE THREAD

**Issue by mgruen** [tsega/meteor-bootstrap3-datetimepicker#34]
Thanks for making this package.

Adding a locale makes it stop working, removing it makes it work again (need "pt" or "pt-BR", but tried several with no luck):

    Template.hextras.rendered=function() { 
       $('.datetimepicker').datetimepicker({
         format:'YYYY-MM-DD',
         locale: 'ru'
       });
    }

**Comment by mgruen** [comment]
Sorry.  Just uploaded my required moment locale file with rzymek's package and it's now working.

meteor add rzymek:moment-locale-pt-br

**Comment by tsega** [comment]
Glad to see you figured it out, I was going to suggest a similar solution :+1:
