### ISSUE TITLE
Timepicker Dropdown Widget Size

### ISSUE THREAD

**Issue by sternetj** [tsega/meteor-bootstrap3-datetimepicker#36]
Is it possible to make the Timepicker Widget Size smaller. It is currently the same size as the datepicker and as a result it has a bunch of uneccessary space.

**Comment by tsega** [comment]
@sternetj the design of the timpicker is inspired by the time scroll pick on iOS devices and the spacious nature of the widget is attributed to the mobile first approach of bootstrap. For your particular case you can easily re-size the elements by manipulating/overriding the css of the widget.
