### ISSUE TITLE
4.13.28 version?

### ISSUE THREAD

**Issue by BradRyan** [tsega/meteor-bootstrap3-datetimepicker#37]
Is there a vew version?  I'd like to use the focusOnShow option discussed in the change logs https://eonasdan.github.io/bootstrap-datetimepicker/Changelog/

**Comment by tsega** [comment]
@BradRyan link is not working but I update the underlying library to the latest version.

**Comment by tsega** [comment]
@BradRyan I've just updated to the latest version, please check if what you are looking for is working.

**Comment by BradRyan** [comment]
Yep was just looking for the latest version basically (Updated my link).  I ended up using modernizr to detect mobile environments with native pickers which seemed to address my problem, but I might consider retaining bootstrap picker in some scenarious so it will be nice to be able to use the new options in the latest release.  Thanks!

**Comment by BradRyan** [comment]
Actually... I'm having issues with the new version.  It doesn't seem to be taking the default moment date that I'm passing.  There is some really weird stuff happening when I pass both minDate and defaultDate.

It's almost like it's misinterpreting my default date as being less than minDate and so it won't show up.  In order to get things working I need to make a larger gap between minDate and defaultDate.

Doesn't work...
```
$('#depart-time-'+routeNo).datetimepicker({
	minDate: moment(),
	defaultDate: moment().add(1, 'h')
});
```
Works...
```
$('#depart-time-'+routeNo).datetimepicker({
	minDate: moment().subtract(1, 'd'),
	defaultDate: moment().add(1, 'h')
});
````

**Comment by BradRyan** [comment]
I'm going to revert back to the previous version for now.  Should I open an issue with Eonasdan/bootstrap-datetimepicker?

**Comment by tsega** [comment]
Please see #38
