### ISSUE TITLE
minDate and defaultDate problems

### ISSUE THREAD

**Issue by BradRyan** [tsega/meteor-bootstrap3-datetimepicker#38]
See comments in #37.  Thought this warranted it's own issue since other's might run into this.  I'll close if you think this question should be posted on the Eonasdan github page (https://github.com/Eonasdan/bootstrap-datetimepicker/issues).

**Comment by tsega** [comment]
@BradRyan I've looked into the #37 example:

```javascript
$('#depart-time-'+routeNo).datetimepicker({
    minDate: moment(),
    defaultDate: moment().add(1, 'h')
});
```

Works perfectly for me! Checkout this [MeteorPad](http://app-94hsk5ar.meteorpad.com/). It might be the case that your selector is picking the wrong DOM element. Please set up a live example at [MeteorPad](http://meteorpad.com) if you need more help.

**Comment by BradRyan** [comment]
Ok thanks I'll give it another shot this week.  I'll close unless I can recreate the issue.
