### ISSUE TITLE
how to use "event change" on datetieme picker?

### ISSUE THREAD

**Issue by thearabbit** [tsega/meteor-bootstrap3-datetimepicker#40]
I want to use `event change` like this
```js
Template.myTpl.events({
   'change .myDateTime': function(e, t){
    ...
   }
})
```
please help me.

**Comment by tsega** [comment]
@thearabbit my apologies for taking forever to reply back. According to the Meteor docs, the *change* event is used for  *checkboxes* and *radio buttons*, [see it here.](http://docs.meteor.com/#/full/eventmaps) 

So instead using the *change* use the *blur* as suggested by Meteor docs. Hit me up if you need any more help. You can also use [MeteorPad.com](http://meteorpad.com) to host live examples.

**Comment by tsega** [comment]
@thearabbit I'm closing this issue because it's been a while. Please feel free to reopen it if your issue is not resolved.
