### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by milincheta** [tsega/meteor-bootstrap3-datetimepicker#41]
Following instructions on https://atmospherejs.com/tsega/bootstrap3-datetimepicker
doesn't work.
Some datails are -for sure- missing.

**Comment by tsega** [comment]
@milincheta that actually works just fine. Take a look at [my example app](http://meteorpad.com/pad/L4MLM5Q8igvvtwSRM/MBDTP).

**Comment by tsega** [comment]
I'm guessing everything is working well for you so I'm closing this issue. Feel free to re-open it if needed.
