### ISSUE TITLE
Time selection does not work on Chrome v45

### ISSUE THREAD

**Issue by salilsethi** [tsega/meteor-bootstrap3-datetimepicker#42]
The plugin was working great on earlier versions of chrome. However, with the latest Chrome v45 the modal shows up blank.

Any help updating the model will be appreciated.

**Comment by tsega** [comment]
@salilsethi my apologies for the late reply, I have Chrome v45 and [my example app](http://meteorpad.com/pad/L4MLM5Q8igvvtwSRM/MBDTP) works just fine. Please provide a little more detail such as 

- What version of Meteor you are using: `$ meteor --version`
- What packages you've installed: `$ meteor list`
