### ISSUE TITLE
Documentation Example gives me "Uncaught TypeError: Cannot read property 'onRendered' of undefined"

### ISSUE THREAD

**Issue by tizol** [tsega/meteor-bootstrap3-datetimepicker#43]
I tried your example, and I put the JavaScript inside a file that I called 
**client.js**
Should I put js code iniside the "if (Meteor.isClient)  {   }"? I tried putting the js in a separate file by itslef and It did not work. 

```js
if (Meteor.isClient) {

  Template.tempName.rendered(function() {
    this.$('.datetimepicker').datetimepicker();
  });

}
```

**schedule.ng.html**
``` html
<template name="tempName">
  <div class="input-group datetimepicker">
  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
  <input class="set-due-date form-control" type="text"/>
</div>
</template>
```

**Comment by tsega** [comment]
@tizol sorry for that, the examples should be update to be `onRendered()` rather than `rendered()`. Will update it now!

**Comment by tizol** [comment]
Thanks!
