### ISSUE TITLE
$('.datepicker') not found if inside an {{ if }} block

### ISSUE THREAD

**Issue by dsjoerg** [tsega/meteor-bootstrap3-datetimepicker#47]
Hi, this may be more of a meteor issue than a meteor-bootstrap3-datetimepicker issue, but I'll file it here in case you realize that it is not a meteor issue.

I have found that if my datetimepicker component happens to be inside an {{ if }} block inside my template, it won't be found by jquery, and instead there will be a prevObject there.  But once I refactored my template so that the datetimepicker had no enclosing {{ if }} block, then everything worked as expected.

**Comment by tsega** [comment]
@dsjoerg most jQuery based packages as this one should be initialized after all the required libraries are loaded, i.e. jQuery itself. That only happen in the `onRendered()` template event. So if you put the initialization code anywhere else it will not find the jQuery library and will raise an error.

Meteor best practice dictates that you shouldn't put code like that in the template files, those should only contain basic logic primarily dealing with displaying data. Good thing that you refactored the code from the template file. :+1:

**Comment by dsjoerg** [comment]
Jquery was found correctly, that wasnt the problem. The problem was that the DOM element was not found, and instead there was a prevObject in its place.



—

**Comment by tsega** [comment]
Hope everything is working well for you now, I'm closing this issue. Feel free to reopen it if needed.
