### ISSUE TITLE
disabledTimeIntervals option broken

### ISSUE THREAD

**Issue by sanneterpstra** [tsega/meteor-bootstrap3-datetimepicker#49]
When trying to use the disabledTimeIntervals option I get the following error:

`Uncaught TypeError: targetMoment.isBetween is not a function`

I use the moment format: 2015-10-23T01:17:00+02:00

Any help on fixing this would be greatly appreciated!

**Comment by tsega** [comment]
@sanneterpstra it looks like the issue is with the underlying datetimepicker library, it has been reported that that options along with a few other are not working as expected. Take a look here, https://github.com/Eonasdan/bootstrap-datetimepicker/issues/982

**Comment by tsega** [comment]
@sanneterpstra it looks like the issue is with the underlying datetimepicker library, it has been reported that that options along with a few other are not working as expected. Take a look here, Eonasdan/bootstrap-datetimepicker#982
