### ISSUE TITLE
Some options doesn't seem to have any effect

### ISSUE THREAD

**Issue by CloneXpert** [tsega/meteor-bootstrap3-datetimepicker#50]
First of all, thanks for the awesome package!

Now, consider the following:
http://meteorpad.com/pad/oYohCHJNHcrRMzHgQ/Copy%20of%20AutoForm-DateTimePicker

What could be wrong here? I'm not able to use many of the available options such as disabledHours, inline and defaultDate. Sidebyside does work...

Also, if I submit the form without picking a dateTime, it'll use the current date. But when later the doc is loaded, it'll pick up the current date again instead of the date used at the time of submission.

Any ideas?

**Comment by tsega** [comment]
@CloneXpert thanks for the complement, but to be honest all I did was create a Meteor Package wrapper for the main library. As you might have encountered somewhere else the problem with that is the issues in the underlying library affect the package; as it is the case for this one. 

It is have been reported that some of the options availble are not working as expected, see here https://github.com/Eonasdan/bootstrap-datetimepicker/issues/982. 

I will try to get the latest fix incorporated into the package as soon as they are released, if you are someone who could lend a hand in fixing the issues, I invite you to do so. Please do so for the main library, https://github.com/Eonasdan/bootstrap-datetimepicker.
