### ISSUE TITLE
Default time set to midnight instead of current time

### ISSUE THREAD

**Issue by aardvarkk** [tsega/meteor-bootstrap3-datetimepicker#51]
When I click inside the datepicker the default time is set to midnight rather than the current time as appears to be the default in examples shown here: https://eonasdan.github.io/bootstrap-datetimepicker/

What's the difference between his demo and mine that makes the time different? I assumed this package just wrapped that version without any real changes.

**Comment by aardvarkk** [comment]
I think I've figured it out. It looks like the website version uses moments version 2.9.0 and this package uses 2.8.4. To get the behaviour I believe I just have to use the later version.

**Comment by aardvarkk** [comment]
Nevermind -- it's not a problem with the `moments` library. The site demo on github.io actually uses an older version of the picker (4.15.35), and I think that's actually what's causing the issue.

**Comment by monasha-s** [comment]
Even I'm getting the same issue.
$('#time').datetimepicker({ format: "hh:mma"});

it shows me the time to be 12:00 am always. How to get the current time?

**Comment by tsega** [comment]
See also issue #61
