### ISSUE TITLE
Problem with "DD-MM-YYYY" format?

### ISSUE THREAD

**Issue by thearabbit** [tsega/meteor-bootstrap3-datetimepicker#52]
I have problem with format
```js
this.$('.datetimepicker').datetimepicker({
   format: 'DD-MM-YYYY'
});
```
It have problem when on focus the text box (it change default value).

**Comment by thearabbit** [comment]
I tried post the issue on `bootstrap3-datetimepicker`, but can't.

**Comment by tsega** [comment]
@thearabbit could you please share a sample app on [Meteor Pad](http://meteorpad.com)

**Comment by thearabbit** [comment]
I tried [datetimepicker pad](http://meteorpad.com/pad/iwEWPJH5RtbmRDWvj/datetimepicker)
But don't work.
Please help me.

**Comment by tsega** [comment]
This is strange, I was having an error while trying the Meteorpad you made, I downloaded it and it works just fine now.

<img width="986" alt="screen shot 2015-12-25 at 10 00 32 pm" src="https://cloud.githubusercontent.com/assets/206924/12004143/fe42eb84-ab52-11e5-8a1d-64115f3c5e7c.png">

Please check if you are getting error in your console while running you app  (not the one on MeteorPad), and if there error do share them here so I can help you.

**Comment by thearabbit** [comment]
Now I tried with `Flat Admin Template` to test `datetimepicker`: [my repo] (https://github.com/thearabbit/flatadmin) 
I work fine to config datetimepicker, but I have problem with format `DD-MM-YYYY`.
(when onfocus on text box, it changed the old value).
Please help me.

Note: pleas see the `client\template\home`.

**Comment by tsega** [comment]
I can now confirm that changing the format to `DD-MM-YYYY` messes up the `datepicker`. I will look into this and get back to you.

**Comment by thearabbit** [comment]
Thanks for your helping.

**Comment by tsega** [comment]
It looks like the [underlying library](https://github.com/Eonasdan/bootstrap-datetimepicker), has disabled submitting issues and only accepts pull requests. Meaning I need to do the fixing and submit my PR, I am not 100% sure if I would be able to do that but I give it a try today.

**Comment by tsega** [comment]
@thearabbit as a temporary fix changing the `-` to a forward slash `/` fixes the issue. Ideally, however, `-` should have worked. 
Again, the bootstrap datetime picker library is not being actively maintained by the owner and a change by a contributor could have introduced this issue, I'm guessing the issue is the [format parsing section](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L1374).

**Comment by thearabbit** [comment]
Thanks, could fix it by manual?

**Comment by thearabbit** [comment]
Now `Eonasdan/bootstrap-datetimepicker` is opened the issue.

**Comment by sasikanth513** [comment]
:+1:  same issue
