### ISSUE TITLE
change

### ISSUE THREAD

**Issue by soyJSus** [tsega/meteor-bootstrap3-datetimepicker#56]
Hi, an attempt Throwing event What The Date Change, but not found.

```javascript
  'change .date': function(event) {
    event.preventDefault();
    console.log("cambio la fecha");
  }
```
I am using Meteorjs

**Comment by tsega** [comment]
@soyJSus can you please paste the error that you are getting on the console.

**Comment by TSDrrodriguez** [comment]
No errors are shown on the console, having the same issue. Change event won't fire when using this.

**Comment by tsega** [comment]
@soyJSus the actual event to listen to should be `dp.change` not  `change`:

```JavaScript
'dp.change .date': function(event) {
    event.preventDefault();
    console.log("cambio la fecha");
  }
```
