### ISSUE TITLE
How to add Submit button

### ISSUE THREAD

**Issue by scheung38** [tsega/meteor-bootstrap3-datetimepicker#57]
I have used the Linked Pickers example, could you show how to add simple Submit Button so that I can add to my MongodB collections in MeteorJS when clicked. Thanks

**Comment by tsega** [comment]
@scheung38 apologies for the late reply. I don't know the particular example (Linked Pickers) you have mentioned, can you please send me a link to it? I believe you want a working example of a form that has a date-time-picker field, is that correct? I can create an example app for this but if there are any special packages that you would like to be included, such as [aldeed:autoform](https://atmospherejs.com/aldeed/autoform).
