### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by jtkeyva** [tsega/meteor-bootstrap3-datetimepicker#59]
Not sure if it's this or aldeed:meteor-autoform-bs-datepicker but I'm getting an Access Denied error now that I've updated Meteor and aldeed:autoform along with a few others.

**Comment by tsega** [comment]
Can you please give more details as to which versions of meteor and packages you are using?
Please run the `meteor --version` & `meteor list` commands within your project folder and paste their output here.
