### ISSUE TITLE
Show Current Time

### ISSUE THREAD

**Issue by monasha-s** [tsega/meteor-bootstrap3-datetimepicker#61]
$('#time').datetimepicker({ format: "hh:mma"});

it shows me the time to be 12:00 am always. How to get the current time?

**Comment by tsega** [comment]
@monasha-s, you can set the `defaultDate` option to `new Date()` to get the current time.

```JavaScript
$('#time').datetimepicker({
  format: "hh:mma",
  defaultDate: new Date()
});
```
The [documentation site](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#defaultdate) for the library is the best place to get info on such stuff. Let me know if you any more help.

**Comment by monasha-s** [comment]
Thank you, Its working now
